[package]
name = "mp32cdda"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
log = "0.4"
env_logger = "0.10"
walkdir = "2.3"
eframe = "0.28"
rfd = "0.11"
single-instance = "0.3"
chrono = "0.4"